name: Build
on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  Publish:
    runs-on: ubuntu-22.04
    env:
        image-url: https://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.1-preinstalled-server-arm64+raspi.img.xz
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install dependencies and prepare
      run: |
           curl -fs https://raw.githubusercontent.com/mafintosh/mount-img/master/install | sh
           sudo apt-get install -y qemu-user-static && sudo systemctl restart systemd-binfmt.service
           mkdir -p ~/image
           mkdir -p ~/build
           mkdir -p ~/mnt
           
    - name: Cache image
      uses: actions/cache@v3
      id: cache-image
      with:
        path: ~/image
        key: ${{ runner.os }}-ubuntu-image-${{ env.image-url }}

    - name: Download image
      if: steps.cache-image.outputs.cache-hit != 'true'
      run: wget ${{ env.image-url }} -O ~/image/ubuntu.img.xz
           
    - name: Unpack image
      run: |
           cp ~/image/ubuntu.img.xz ~/build/ubuntu.img.xz
           unxz ~/build/ubuntu.img.xz
      
    - name: Mount image
      run: mount-img ~/build/ubuntu.img ~/mnt -p 2
           
    - name: Apply changes
      run: |
           chmod +x prepare.sh
           sudo mkdir -p ~/mnt/home/monero
           sudo cp update.sh ~/mnt/home/monero/update.sh && chmod +x ~/mnt/home/monero/update.sh
           sudo cp monerod.conf ~/mnt/home/monero/monerod.conf && chmod +x ~/mnt/home/monero/monerod.conf
           sudo cp monerod.service ~/mnt/home/monero/monerod.service && chmod +x ~/mnt/home/monero/monerod.service
           sudo chroot ~/mnt ./prepare.sh
           
    - name: Unmount image
      run: sudo umount ~/mnt
      
    - name: Compress image
      run: xz --compress ~/build/ubuntu.img
    
    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu.img.xz
        path: ~/build/ubuntu.img.xz
