name: Build
on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  Publish:
    runs-on: ubuntu-22.04
    env:
        image-url: https://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.1-preinstalled-server-arm64+raspi.img.xz
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install dependencies and prepare
      run: |
           curl -fs https://raw.githubusercontent.com/mafintosh/mount-img/master/install | sh
           sudo apt-get install -y qemu-user-static && sudo systemctl restart systemd-binfmt.service
           mkdir -p ~/image
           mkdir -p ~/mnt
           
    - name: Cache image
      uses: actions/cache@v3
      with:
        path: ~/image
        key: ${{ runner.os }}-build-${{ env.image-url }}

    - name: Download and unpack image
      run: | 
           wget ${{ env.image-url }} -O ~/image/ubuntu.img.xz
           unxz ~/image/ubuntu.img.xz
      
    - name: Mount image
      run: mount-img ~/image/ubuntu.img ~/mnt -p 2
           
    - name: Apply changes
      run: |
           chmod +x prepare.sh
           ./prepare.sh
           
    - name: Unmount image
      run: sudo umount ~/mnt
      
    - name: Compress image
      run: xz --compress ~/image/ubuntu.img
    
    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu.img.xz
        path: ~/image/ubuntu.img.xz
